### PR TITLE
init.sls: update to Confluent 5.0

### PR DESCRIPTION
**Pull request by adelcast**
Signed-off-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>

### CODE REVIEW

**Comment by adelcast** [comment]
@igalic  any chance we can get this merged? Its been open for 4 months....

**Comment by igalic** [comment]
@adelcast i'm afraid i don't have merge access here!

**Comment by aboe76** [comment]
@adelcast and @igalic sorry this took so long, it must have slipped by...

**Comment by blbradley** [comment]
@igalic You should ask to be part of the Contributors team. Neither I or @aboe76 have access to do such. And I don't know who to ask these days.

**Comment by myii** [comment]
@blbradley @igalic I recently got access by asking Daniel Wallace in the [SaltStack Community #formulas group](https://saltstackcommunity.slack.com/messages/C7LG8SV54) on Slack.

**Comment by igalic** [comment]
thank you very much for your encouragement! and usually i would follow such advice immediately.
however, i've only had very brief encounters with Salt, while mentoring a colleague in it.

**Pull request merged**
